<<<<<<< HEAD
# AIプロバイダー設定
ai_providers:
  use_vertexai: true
  use_openai: false
  use_anthropic: false
  google_api_key: "your-google-api-key"
  openai_api_key: "your-openai-key"
  anthropic_api_key: "your-anthropic-key"

# システム監視設定
system_settings:
  cpu_threshold: 80
  memory_threshold: 85
  log_level: INFO

# エージェント設定
agents:
  - id: main_agent
    type: autonomous
    model: gemini-pro
    max_tokens: 2000
    temperature: 0.7
    rate_limit:
      requests: 60
      period: 60

# データベース設定
database:
  path: desktop_agent.db
  backup_interval: 3600

  - id: backup_agent
    type: worker
    model: gpt-4-turbo
=======
# AIプロバイダー設定
ai_providers:
  use_vertexai: true
  use_openai: false
  use_anthropic: false
  google_api_key: "your-google-api-key"
  openai_api_key: "your-openai-key"
  anthropic_api_key: "your-anthropic-key"

# システム監視設定
system_settings:
  cpu_threshold: 80
  memory_threshold: 85
  log_level: INFO

# エージェント設定
agents:
  - id: main_agent
    type: autonomous
    model: gemini-pro
    max_tokens: 2000
    temperature: 0.7
    rate_limit:
      requests: 60
      period: 60

# データベース設定
database:
  path: desktop_agent.db
  backup_interval: 3600

  - id: backup_agent
    type: worker
    model: gpt-4-turbo
>>>>>>> 42de7d643d987d98855d441372a3931e7de31809
    max_tokens: 1000 